workflows: flutter
  android-apk:
    name: Build APK
    environment: ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
scripts:
  - flutter pub get
  - flutter build apk --release --verbose  # Added verbose for detailed logs
